const SEND_SMS_VERIFICATION = 'SEND_SMS_VERIFICATION[AUTH]';
const VERIFY_SMS = 'VERIFY_SMS[AUTH]';
const SET_DEFAULT_HEADERS = 'SET_DEFAULT_HEADERS[AUTH]';
const SET_LOADING = 'SET_LOADING[AUTH]';
const SET_REGISTRATION_DATA = 'SET_REGISTRATION_DATA[AUTH]';
const SET_USER_DATA = 'SET_USER_DATA[AUTH]';
const LOGOUT = 'LOGOUT[AUTH]';

const ADD_USER_ADDRESS = 'ADD_USER_ADDRESS[USER_DATA]';
const EDIT_USER_DATA = 'EDIT_USER_DATA[USER_DATA]';
const GET_USER_DATA = 'GET_USER_DATA[USER_DATA]';

export {SEND_SMS_VERIFICATION, SET_DEFAULT_HEADERS, SET_LOADING, VERIFY_SMS, SET_REGISTRATION_DATA, SET_USER_DATA, ADD_USER_ADDRESS, GET_USER_DATA, LOGOUT, EDIT_USER_DATA};
