const GET_JUNK_COLLECTION = 'GET_JUNK_COLLECTION[CALL_CAR]';
const CREATE_ORDER_COLLECTION = 'CREATE_ORDER_COLLECTION[CALL_CAR]';
const SET_LOADING = 'SET_LOADING[CALL_CAR]';
const UPLOAD_PHOTO = 'UPLOAD_PHOTO[CALL_CAR]';
const REMOVE_PHOTO = 'REMOVE_PHOTO[CALL_CAR]';
const CHOSE_ADDRESS = 'CHOSE_ADDRESS[CALL_CAR]';
const SET_DEFAULT_ORDER = 'SET_DEFAULT_ORDER[CALL_CAR]';
const CANCEL_ORDER = 'CANCEL_ORDER[CALL_CAR]';
const SHOW_SUCCESS_ORDER_CREATE_POPUP = 'SHOW_SUCCESS_ORDER_CREATE_POPUP[CALL_CAR]';

const GET_JUNKS_COLLECTION_ORDERS_LIST = 'GET_JUNKS_COLLECTION_ORDERS_LIST[CALL_CAR]';
const SEND_COLLECTOR_REVIEW = 'SEND_COLLECTOR_REVIEW[CALL_CAR]';


export {
  SET_LOADING,
  GET_JUNK_COLLECTION,
  CREATE_ORDER_COLLECTION,
  GET_JUNKS_COLLECTION_ORDERS_LIST,
  UPLOAD_PHOTO,
  CHOSE_ADDRESS,
  SET_DEFAULT_ORDER,
  REMOVE_PHOTO,
  CANCEL_ORDER,
  SHOW_SUCCESS_ORDER_CREATE_POPUP,
  SEND_COLLECTOR_REVIEW,
};
