const SET_ERROR = 'SET_ERROR';
const GET_WAREHOUSES = 'GET_WAREHOUSES[ADD_INFO]';
const SET_LOADING = 'SET_LOADING[ADD_INFO]';
const GET_BANNERS = 'GET_BANNERS[ADD_INFO]';
const SET_CHECKED_ITEM_STATUS = 'SET_CHECKED_ITEM_STATUS[ADD_INFO]';


const WITHDRAW = 'WITHDRAW[WITHDRAW]';
const GET_WITHDRAWS = 'GET_WITHDRAWS[WITHDRAW]';


export {SET_ERROR, GET_WAREHOUSES, SET_LOADING, GET_BANNERS, WITHDRAW, GET_WITHDRAWS, SET_CHECKED_ITEM_STATUS};
